media: /
content:
  - name: /
    label: Posts
    type: collection
    path: /
    fields:
      - { name: title, label: Title, type: string }
      - { name: layout, label: Layout, type: string, default: post, hidden: true }
      - { name: date, label: Date, type: date }
      - { name: categories, label: Category, type: string, default: [post], hidden: true }
      - { name: permalink, label: Permalink, type: string }
      - { name: search_exclude, label: Searchable?, type: boolean, default: true }
      - { name: nav_exclude, hidden: true, type: boolean, default: true }