name: kawapa | C++
description: 
meta_description: 

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: "/"
domain_name: ""
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "kawapa"

# Disqus config
disqus-shortname: ""