name: CppDev
description: 
meta_description: 

markdown: kramdown
logo: false
paginate: 15
baseurl: "/"
domain_name: ""
google_analytics: "UA-XXXXXXXX-X"

# Details for the RSS feed generator
url: ""
author: "kawapa"

# Disqus config
disqus-shortname: ""
plugins:
  - jekyll-gist
  - jekyll-paginate